# THIS IS AN EXAMPLE ON HOW YOU SHOULD CONFIGURE YOUR hugo.toml
# See this hugo.toml in action at https://github.com/1bl4z3r/hermit-V2/blob/staging/hugo.toml
# Example Site is Staging branch, acessible at https://github.com/1bl4z3r/hermit-V2/tree/staging
# To see what each config does, refer to https://1bl4z3r.github.io/hermit-V2/en/posts/explaining-configs/
# Open Issue or Pull Request at https://github.com/1bl4z3r/hermit-V2

baseURL = "https://indigraphs.wiki/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
theme = ["hugo-chart", "hermit-v2"]

[languages]
 [languages.en]
  title = 'IndiGraphs.Wiki'
 [languages.en.params]
    homeSubtitle = "Isn't data beautiful ?"
 weight = 1
#  [languages.fr]
#    title = 'CHANGE ME(FR)'
#    [languages.fr.params]
#      homeSubtitle = "CHANGE ME"
#    weight = 2
#  [languages.it]
#    title = 'CHANGE ME(IT)'
#    [languages.it.params]
#      homeSubtitle = "CHANGE ME"
#    weight = 3
 
languageCode = "en-us"

# title = "CHANGE ME"
# enableGitInfo = true

pygmentsCodefences  = true
pygmentsUseClasses  = true
#hasCJKLanguage = true

rssLimit = 10

copyright = "IndiGraphs.Wiki"
enableEmoji = true

# googleAnalytics = "UA-123-45"
# disqusShortname = "CHANGE ME"

#[params.author]
 # name = "CHANGE SITE AUTHOR"
  #about = "CHANGE SITE AUTHOR ABOUT"

[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[taxonomies]
  tag = "tags"
  # Categories are disabled by default.
  # category = "categories"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  description = "IndiGraphs is An Open Source repository of common data depicted through clear and informative graphs and infographics."
  # images = [""]
  themeColor = "#494f5c"

  homeSubtitle = "Made and maintained by and for Indians"
  footerCopyright = "IndiGraphs.Wiki"
  # bgImg = ""
  # gitUrl = "https://github.com/1bl4z3r/hermit-V2/tree/staging"

  justifyContent = false

  relatedPosts = true
  code_copy_button = true

  homeSubtitlePrinter = true
  scrollToTop = true 
  global_mathjax = false
  readTime = true
  readTimeSeparator = "|"
  # legacyLayout = false
  shareSocial = true
  # googleTagManager = "GTM-XXXXXXXX"
  # tagSymbol = "#"
  # categorySymbol = "⊲"
  
  [[params.socialLinks]]
    name = "mastodon"
    url = "https://joinmastodon.org/"

  [[params.socialLinks]]
    name = "x"
    url = "https://twitter.com/"

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/1bl4z3r/hermit-V2/tree/staging"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 20
    
[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files